### ISSUE TITLE
Problem with setting up tests

### ISSUE THREAD

**Issue by FranciszekMalcher** [TenKeyLabs/dappwright#78]
Readme file dosen't provide clear instructions on how to use it.

So part in global-setup.js works fine:

```

import dappwright, { MetaMaskWallet } from '@tenkeylabs/dappwright';
import playwright from 'playwright';

module.exports = async (config) => {
	const [metamask, page, context] = await dappwright.bootstrap('', {
		wallet: 'metamask',
		version: MetaMaskWallet.recommendedVersion,
	});

	await context.close();
};
```

but in my-test.js I Have Error:
```

const base = require('@playwright/test');
const { LandingPage } = require('../pages/landing-page.js');
const { ConnectWalletModal } = require('../pages/connect-wallet-modal.js');
const { ConnectMetamaskWalletModal } = require('../pages/connect-metamask-wallet-modal.js');
import dappwright, { MetaMaskWallet } from '@tenkeylabs/dappwright';

exports.test = base.test.extend({
	context: async ({}, use) => {
		// Launch context with the same session from global-setup
		const context = await dappwright.launch('', {
			metamaskVersion: MetaMaskWallet.recommendedVersion,
		});
		// Unlock the wallet
		await metamask.unlock();
		await use(context);
		await context.close();
	},

	metamask: async ({ context }, use) => {
		const metamask = await dappwright.getWallet('metamask', context);
		await use(metamask);
	},

	landingPage: async ({ page }, use) => {
		await use(new LandingPage(page));
	},

	connectWalletModal: async ({ page }, use) => {
		await use(new ConnectWalletModal(page));
	},

	connectMetamaskWalletModal: async ({ page }, use) => {
		await use(new ConnectMetamaskWalletModal(page));
	},
});


exports.expect = base.expect;

```

Error:
```

    Error: Wallet undefined not supported

       at my-test.js:10

       8 |      context: async ({}, use) => {
       9 |              // Launch context with the same session from global-setup
    > 10 |              const context = await dappwright.launch('metamask', {
         |                                               ^
      11 |                      metamaskVersion: MetaMaskWallet.recommendedVersion,
      12 |              });
      13 |              // Unlock the wallet

        at getWalletType (C:\Users\malch\OneDrive\Pulpit\Franek\Praca\locklabs\DotEarthTests\dotearth-game-frontend\node_modules\@tenkeylabs\dappwright\src\wallets\wallets.ts:21:26)
        at Object.launch (C:\Users\malch\OneDrive\Pulpit\Franek\Praca\locklabs\DotEarthTests\dotearth-game-frontend\node_modules\@tenkeylabs\dappwright\src\launch.ts:15:18)
        at Object.context [as fn] (C:\Users\malch\OneDrive\Pulpit\Franek\Praca\locklabs\DotEarthTests\dotearth-game-frontend\e2e\tests\my-test.js:10:36)
```

I'm not sure what should be in context then, help please :)

**Comment by osis** [comment]
Really sorry about this. We're working on updated docs and an example application.

For now, can you try the change in https://github.com/TenKeyLabs/dappwright/commit/e8ad10eb9cd364b534d6a39351d305f0b7b940ea and see if that helps?

**Comment by FranciszekMalcher** [comment]
Yes, it helps, Thank you.

but I  had to use proper context:

```
	context: async ({}, use) => {
		const context = await dappwright.launch('', {
			wallet: 'metamask',
			version: MetaMaskWallet.recommendedVersion,
		});
		await context.wallet.unlock(); // from 'metamask.unlock()'
		await use(context.browserContext); // from 'use(context)'
		await context.browserContext.close(); // from 'context.close()'
	},
```
Worth further updating of Readme with those lines.
