### ISSUE TITLE
Timeout during bootstraping is too short, causes flaky tests.

### ISSUE THREAD

**Issue by FranciszekMalcher** [TenKeyLabs/dappwright#93]
I have wallet configured in global-setup.js.

Some times that is failing: 

```
Running 5 tests using 1 worker
Running tests on metamask version 10.25.0
Downloading extension...
page.waitForSelector: Timeout 5000ms exceeded.
=========================== logs ===========================
waiting for locator('xpath=//label[contains(.,\'1.\')]/following-sibling::textarea|//label[contains(.,\'1.\')]/following-sibling::*//input|//h6[contains(.,\'1.\')]/parent::node()/parent::node()/following-sibling::input|//h6[contains(.,\'1.\')]/parent::node()/parent::node()/following-sibling::*//input|//span[contains(.,\'1.\')]/parent::node()/parent::node()/following-sibling::*//input|//span[contains(.,\'1.\')]/following-sibling::*//input') to be visible
============================================================
    at getInputByLabel (/builds/dotearth/qa/dotearth-game-frontend/node_modules/@tenkeylabs/dappwright/src/helpers/selectors.ts:12:8)
    at _catch (/builds/dotearth/qa/dotearth-game-frontend/node_modules/@tenkeylabs/dappwright/src/helpers/actions.ts:38:19)
    at typeOnInputField (/builds/dotearth/qa/dotearth-game-frontend/node_modules/@tenkeylabs/dappwright/src/helpers/actions.ts:37:7)
    at _temp (/builds/dotearth/qa/dotearth-game-frontend/node_modules/@tenkeylabs/dappwright/src/wallets/metamask/setup/setupActions.ts:45:11)
    at _temp (/builds/dotearth/qa/dotearth-game-frontend/node_modules/@tenkeylabs/dappwright/src/wallets/metamask/setup/setupActions.ts:47:63)
    at _forOf (/builds/dotearth/qa/dotearth-game-frontend/node_modules/@tenkeylabs/dappwright/src/wallets/metamask/setup/setupActions.ts:47:63)
    at /builds/dotearth/qa/dotearth-game-frontend/node_modules/@tenkeylabs/dappwright/src/wallets/metamask/setup/setupActions.ts:47:63
```

It would be nice to increase that timeout.

My solution to that is to put retries on global-setup that:
https://github.com/microsoft/playwright/discussions/11371

**Comment by osis** [comment]
Thanks for reporting. Did you have any information on which step/action is failing?

**Comment by FranciszekMalcher** [comment]
No, can't catch that.

**Comment by osis** [comment]
The new examples and guidance for setup removes the bootstrapping process from the globalSetup, which is a part of the process that is hard to debug and diagnose.
